# Generated by Django 4.1.2 on 2022-11-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('subClasificacion', models.ForeignKey(db_column='id_subClasificacion', on_delete=django.db.models.deletion.CASCADE, to='clasificacion.subclasificacionarticulos')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'db_table': 'eng_articulos',
            },
        ),
    ]
