# Generated by Django 4.1.2 on 2022-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre_razon', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('curp', models.CharField(blank=True, max_length=20, null=True)),
                ('imss', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=80, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('pais', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'eng_empresas',
            },
        ),
    ]
