# Generated by Django 4.1.2 on 2022-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubClasificacionArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=40)),
                ('clasificacion', models.CharField(choices=[('INS', 'Insumos'), ('MED', 'Medicamentos')], max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SubClasificacion Articulos',
                'verbose_name_plural': 'SubClasificaciones Articulos',
                'db_table': 'eng_subclasificacion_articulos',
            },
        ),
    ]
