# Generated by Django 4.1.2 on 2022-11-18 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fincas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=80, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('pais', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'db_table': 'eng_fincas',
            },
        ),
        migrations.CreateModel(
            name='EspacioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('POT', 'Potrero'), ('COR', 'Corral')], max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('hectareas', models.CharField(blank=True, max_length=80, null=True)),
                ('follaje', models.CharField(blank=True, max_length=20, null=True)),
                ('finca', models.ForeignKey(db_column='id_fincas', on_delete=django.db.models.deletion.CASCADE, to='fincas.fincas')),
            ],
            options={
                'verbose_name': 'Potrero',
                'verbose_name_plural': 'Potreros',
                'db_table': 'eng_espacio_fisico',
            },
        ),
    ]
