# Generated by Django 4.1.2 on 2022-11-30 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Foros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Foro',
                'verbose_name_plural': 'Foro',
                'db_table': 'foros',
            },
        ),
        migrations.DeleteModel(
            name='SubClasificacionArticulos',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='foro',
            field=models.ForeignKey(db_column='id_foro', on_delete=django.db.models.deletion.CASCADE, to='foros.foros'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
