# Generated by Django 4.1.2 on 2022-12-01 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foros', '0002_comentarios_foros_delete_subclasificacionarticulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foros',
            name='creador',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
