# Generated by Django 4.1.2 on 2022-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('INS', 'Insumos'), ('MED', 'Medicamentos')], max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('articulos', models.ManyToManyField(to='articulos.articulos')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'db_table': 'eng_almacenes',
            },
        ),
    ]
